<?php 

function my_project_preprocess(&$variables, $hook) {
	
	$header_block = views_embed_view('header', 'block_1');
	$variables['header_block'] = $header_block;

	$homepage_block = views_embed_view('homepage', 'block_1');
	$variables['homepage_block'] = $homepage_block;

	$portfolio_block = views_embed_view('portofio', 'block_1');
	$variables['portfolio_block'] = $portfolio_block;

	$projects_block = views_embed_view('projects', 'page_1');
	$variables['projects_block'] = $projects_block;	
	
}