<?php 

function my_project_preprocess(&$variables, $hook) {
	$header_block = views_embed_view('header', 'block_1');
	$variables['header_block'] = $header_block;

	$homepage_block = views_embed_view('homepage', 'block_1');
	$variables['homepage_block'] = $homepage_block;

	$portfolio_block = views_embed_view('portofio', 'block_1');
	$variables['portfolio_block'] = $portfolio_block;

	$skills_block = views_embed_view('services', 'block_1');
	$variables['services_block'] = $services_block;

	$blog_block = views_embed_view('blog_post', 'block_1');
	$variables['blog_post'] = $blog_post;

	$contact_block = views_embed_view('contact_block', 'block_1');
	$variables['contact_block'] = $contact_block;

	
}